<?php

class FilterSanitize {
 
    const FILTER_SANITIZE_STRING = FILTER_SANITIZE_STRING;
    const FILTER_SANITIZE_STRIPPED = FILTER_SANITIZE_STRIPPED;
    const FILTER_SANITIZE_ENCODED = FILTER_SANITIZE_ENCODED;
    const FILTER_SANITIZE_SPECIAL_CHARS = FILTER_SANITIZE_SPECIAL_CHARS;
    const FILTER_SANITIZE_EMAIL = FILTER_SANITIZE_EMAIL;
    const FILTER_SANITIZE_URL = FILTER_SANITIZE_URL;
    const FILTER_SANITIZE_NUMBER_INT = FILTER_SANITIZE_NUMBER_INT;
    const FILTER_SANITIZE_NUMBER_FLOAT = FILTER_SANITIZE_NUMBER_FLOAT;
    const FILTER_SANITIZE_MAGIC_QUOTES = FILTER_SANITIZE_MAGIC_QUOTES;
    
    public static function values() {
        return array(
            self::FILTER_SANITIZE_STRING,
            self::FILTER_SANITIZE_STRIPPED,
            self::FILTER_SANITIZE_ENCODED,
            self::FILTER_SANITIZE_SPECIAL_CHARS,
            self::FILTER_SANITIZE_EMAIL,
            self::FILTER_SANITIZE_URL,
            self::FILTER_SANITIZE_NUMBER_INT,
            self::FILTER_SANITIZE_NUMBER_FLOAT,
            self::FILTER_SANITIZE_MAGIC_QUOTES
        );
    }
    
}
