<?php

class FilterFlag {
    
    const FILTER_FLAG_NONE = FILTER_FLAG_NONE;
    
    const FILTER_REQUIRE_SCALAR = FILTER_REQUIRE_SCALAR;
    const FILTER_REQUIRE_ARRAY = FILTER_REQUIRE_ARRAY;
    const FILTER_FORCE_ARRAY = FILTER_FORCE_ARRAY;
    
    const FILTER_NULL_ON_FAILURE = FILTER_NULL_ON_FAILURE;
    
    const FILTER_FLAG_ALLOW_OCTAL = FILTER_FLAG_ALLOW_OCTAL;
    const FILTER_FLAG_ALLOW_HEX = FILTER_FLAG_ALLOW_HEX;
    const FILTER_FLAG_STRIP_LOW = FILTER_FLAG_STRIP_LOW;
    const FILTER_FLAG_STRIP_HIGH = FILTER_FLAG_STRIP_HIGH;
    const FILTER_FLAG_STRIP_BACKTICK = FILTER_FLAG_STRIP_BACKTICK;
    const FILTER_FLAG_ENCODE_LOW = FILTER_FLAG_ENCODE_LOW;
    const FILTER_FLAG_ENCODE_HIGH = FILTER_FLAG_ENCODE_HIGH;
    const FILTER_FLAG_ENCODE_AMP = FILTER_FLAG_ENCODE_AMP;
    const FILTER_FLAG_NO_ENCODE_QUOTES = FILTER_FLAG_NO_ENCODE_QUOTES;
    //const FILTER_FLAG_EMPTY_STRING_NULL = FILTER_FLAG_EMPTY_STRING_NULL;
    const FILTER_FLAG_ALLOW_FRACTION = FILTER_FLAG_ALLOW_FRACTION;
    const FILTER_FLAG_ALLOW_THOUSAND = FILTER_FLAG_ALLOW_THOUSAND;
    const FILTER_FLAG_ALLOW_SCIENTIFIC = FILTER_FLAG_ALLOW_SCIENTIFIC;
    const FILTER_FLAG_SCHEME_REQUIRED = FILTER_FLAG_SCHEME_REQUIRED;
    const FILTER_FLAG_HOST_REQUIRED = FILTER_FLAG_HOST_REQUIRED;
    const FILTER_FLAG_PATH_REQUIRED = FILTER_FLAG_PATH_REQUIRED;
    const FILTER_FLAG_QUERY_REQUIRED = FILTER_FLAG_QUERY_REQUIRED;
    const FILTER_FLAG_IPV4 = FILTER_FLAG_IPV4;
    const FILTER_FLAG_IPV6 = FILTER_FLAG_IPV6;
    const FILTER_FLAG_NO_RES_RANGE = FILTER_FLAG_NO_RES_RANGE;
    const FILTER_FLAG_NO_PRIV_RANGE = FILTER_FLAG_NO_PRIV_RANGE;
}
